### ISSUE TITLE
How did you get the XLS table containing "total number single nucleotide variants"?

### ISSUE THREAD

**Issue by agentdr1** [hwanglab/tcga_tmb_prediction#8]
Hi, 

how did you get the xls table containing the "total number single nucleotide variants" which is used to determine the TMB? In other words, which file from GDC did you use? I want to perform a similar prediction task, on TCGA COAD though. 

Best,
Daniel

**Comment by jeanrclemenceau** [comment]
Hello Daniel,

We downloaded the spreadsheet from the Supplemental Table1 in one of the publications associated with the TCGA BLCA dataset:

https://www.sciencedirect.com/science/article/pii/S0092867417310565#app2

I would suggest that you take a look at the publication associated with TCGA COAD.

Thank you for your interest!
